### PR TITLE
Remove all homepage caching

### PR DESCRIPTION
**Pull request by tadhg-ohiggins**
First-pass attempt to fix the incorrect “days remaining” display.

### CODE REVIEW

**Comment by tadhg-ohiggins** [comment]
Merging my own code here, but other people have looked closely at it.

**Comment by cmc333333** [comment]
Heads up on that we aren't using Django's caching Middleware, so this turns
off all caching on these pages. That might be an issue particularly for the
home page, which sees a lot of network traffic before it can be built.

**Comment by cmc333333** [comment]
S/middleware/site-wide cache

We do, in fact use the middleware, but we don't have it on for all pages
due to needing dynamic results from time to time. Best to check the -site
and -core settings to see specifics

**Comment by tadhg-ohiggins** [comment]
For the first-step fix, I decided that not showing the wrong days-remaining count was more important than performance. Jacob suggested that caching the expensive results in the view code for these particular pages would be more straightforward than using the caching middleware, and I think he's right about that, so I think that will be my next step.

**Pull request merged**
